




services:
  postgres:
    image: postgres:15.5-alpine3.19
    volu
    mes:
      - ./keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - keycloak_network
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/config/realm-export.json
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - KC_PROXY=edge
      - KC_HOSTNAME=some-external-site.somewhere
      - PROXY_ADDRESS_FORWARDING=true
      - LOG_LEVEL=ALL
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm.json
       #Don't know how to connect to postgres database. NONE of these seems work:
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DATABASE=postgres
      - KC_DB_VENDOR=POSTGRES
      - KC_DB_ADDR=postgres
      - KC_DB_DATABASE=keycloak
      - KC_DB_USER=keycloak
      - KC_DB_SCHEMA=public
      - KC_DB_PASSWORD=password
      - DATABASE=postgres
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./config:/config
    command:
      - start
    networks:
      - keycloak_postgres_data

networks:
  keycloak_network:
    name: keycloak_network
    driver: bridge

volumes:
  keycloak_postgres_data:
    driver: local