
server:
  port: 8082

spring:
  application:
    name: borrowing-management-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  #rabbitmq:
  #  addresses: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}}

logging:
  level:
    ROOT: info
    org.hibernate.SQL: info
    sn.ouznoreyni.bookcatalogservice: info


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${GATEWAY_SERVICE_URL:http://localhost:8761/eureka}
    healthcheck:
      enabled: false
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones:
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}


management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - gateway
          - health
          - info
          - logfile
          - loggers
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  info:
    git:
      mode: full
    env:
      enabled: true
  observations:
    key-values:
      application: ${spring.application.name}
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0




